# Generated by Django 4.2.7 on 2025-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('web-development', 'Web Development Project'), ('mobile-app', 'Mobile App Development'), ('cloud-services', 'Cloud & DevOps Services'), ('consultation', 'Technical Consultation'), ('maintenance', 'Maintenance & Support'), ('other', 'Other')], default='other', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(choices=[('5000-10000', '$5,000 - $10,000'), ('10000-25000', '$10,000 - $25,000'), ('25000-50000', '$25,000 - $50,000'), ('50000+', '$50,000+')], max_length=20)),
                ('services', models.JSONField(default=list, help_text='List of selected services')),
                ('timeline', models.CharField(choices=[('asap', 'ASAP'), ('1-month', 'Within 1 month'), ('2-3-months', '2-3 months'), ('3-6-months', '3-6 months'), ('flexible', 'Flexible')], max_length=20)),
                ('description', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
