# Generated by Django 4.2.7 on 2025-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Wambui Kamau', max_length=200)),
                ('subtitle', models.CharField(default='Full-Stack Developer & IT Solutions Expert', max_length=200)),
                ('bio', models.TextField(help_text='Your professional bio')),
                ('mission', models.TextField(help_text='Your mission statement')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('years_experience', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(default=0)),
                ('cv_file', models.FileField(blank=True, help_text='Upload your CV/Resume', null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech_stack', models.JSONField(default=list, help_text='List of technologies used as JSON array')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('case_study_url', models.URLField(blank=True, help_text='Case study URL', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('completed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-completed_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='🔧', help_text='Emoji or icon class', max_length=100)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of features as JSON array')),
                ('price_range', models.CharField(blank=True, help_text="e.g., '$5,000 - $10,000'", max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency percentage (0-100)')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(max_length=100)),
                ('client_company', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
